### ISSUE TITLE
脚注相关问题

### ISSUE THREAD

**Issue by bt-njust** [shenweiyan/Markdown2Html#10]
```markdown
链接：[文字](链接)
脚注：[文字](脚注解释 "脚注名字")
```
其中「脚注解释」里面不能包含空格，否则脚注失效——也就是不能适用于包含英文的脚注解释

另外，「脚注解释」和「脚注名字」之间的冒号是否可以取消？如「Front-end web development: https://en.wikipedia.org/wiki/Front-end_web_development」，因为后半部分已经是一个斜体，再加个冒号感觉非常的不和谐。请问这里在css设置中对应哪个属性？

谢谢！

**Comment by shenweiyan** [comment]
1. 「脚注解释」里面不能包含空格，否则脚注失效。
   目前好像的确是这样的。对于有空格的脚注解释目前的一个解决方法是把空格换成`&nbsp;`，例如：
   ```
   脚注：[文字](This&nbsp;is&nbsp;a&nbsp;test "脚注名字")
   ```

2. 「脚注解释」和「脚注名字」之间的冒号是否可以取消？
   这个冒号不是通过 css 来控制的，目前暂时无法调整。

再次感谢您的建议🌹

**Comment by bt-njust** [comment]
感谢回复！谢谢您的贡献！
