### ISSUE TITLE
多级列表与引用块中不支持软换行

### ISSUE THREAD

**Issue by e-chehil** [shenweiyan/Markdown2Html#2]
- the United Nations Security Council
  联合国安全理事会
- This play is supported by a grant from the local arts council.
  这出戏由当地艺术委员会出资赞助。
```markdown
- the United Nations Security Council
  联合国安全理事会
- This play is supported by a grant from the local arts council.
  这出戏由当地艺术委员会出资赞助。
```
实际效果
![图片](https://github.com/shenweiyan/Markdown2Html/assets/129576232/b8afb0e5-1242-4c03-9d38-5df8a2b9fde5)

**Comment by shenweiyan** [comment]
> * the United Nations Security Council
>   联合国安全理事会
> * This play is supported by a grant from the local arts council.
>   这出戏由当地艺术委员会出资赞助。
> 
> ```
> - the United Nations Security Council
>   联合国安全理事会
> - This play is supported by a grant from the local arts council.
>   这出戏由当地艺术委员会出资赞助。
> ```
> 
> 实际效果 ![图片](https://private-user-images.githubusercontent.com/129576232/309515089-b8afb0e5-1242-4c03-9d38-5df8a2b9fde5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MTQ0NzksIm5iZiI6MTcwOTUxNDE3OSwicGF0aCI6Ii8xMjk1NzYyMzIvMzA5NTE1MDg5LWI4YWZiMGU1LTEyNDItNGMwMy05ZDM4LTVkZjhhMmI5ZmRlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQwMTAyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDNjN2EyODY4MjY5YWVmOGNjOTIzMzE4YmY3NzU2OTQ1NDdjMDhiZWMwMmQ4ZjkyZjRiOWVkNzhkYmYwZWIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9pO732uPOcFTWlWcOlgEgLmTg0kH0dUn6Uk84uiJeR8)

在列表的前一行结果多加几个空格即可，如截图：

![image](https://github.com/shenweiyan/Markdown2Html/assets/26101369/d7985a68-1929-4ffc-a179-999461c67895)
