### ISSUE TITLE
打算写一个这样的公众号排版工具，应该如何上手呢？

### ISSUE THREAD

**Issue by chenxin3170** [shenweiyan/Markdown2Html#5]
这就是我想做的项目，自己写公众号排版真费事儿，就打算写一个，请教一下，我应该如何上手呢，给点思路

**Comment by shenweiyan** [comment]
好像也没什么可以建议的，我觉得基于一个你比较喜欢的开源项目，然后修修补补打造成你喜欢的样子，应该就足够了
