### ISSUE TITLE
选择 Mac 风格没有生效

### ISSUE THREAD

**Issue by pc-study** [shenweiyan/Markdown2Html#6]
![image](https://github.com/user-attachments/assets/df59851c-5795-4941-8cb0-8677a3fe0198)

**Comment by pc-study** [comment]
![image](https://github.com/user-attachments/assets/8420938f-7ec4-41a3-9274-78cff3ff0333)
感觉是这个图片无法访问

**Comment by pc-study** [comment]
![image](https://github.com/user-attachments/assets/c53d4c66-05c3-4d4a-85b5-eb0cbf3e0b7c)

**Comment by shenweiyan** [comment]
感谢反馈，的确是图片的问题，[e3c7f79](https://github.com/shenweiyan/Markdown2Html/commit/e3c7f7979036c2d3804f5671ecbc1c30ffe9fe04) 中已经修复了。
